---
- hosts: webservers
  become: True
  tasks:
    - name: Copy Deploy files
      copy:
        src: ./
        dest: ~/hello-go-api/
    - name: Deploy in Docker compose
      docker_compose:
        project_src: ~/hello-go-api/
